# Generated by Django 3.1.2 on 2021-02-24 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=2)),
                ('college', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=50)),
                ('avg_points', models.CharField(max_length=10)),
                ('avg_assist', models.CharField(max_length=10)),
                ('avg_rebounds', models.CharField(max_length=10)),
                ('avg_steals', models.CharField(max_length=10)),
                ('avg_blocks', models.CharField(max_length=10)),
                ('avg_turnovers', models.CharField(max_length=10)),
                ('FG_percentage', models.CharField(max_length=10)),
                ('TP_percantage', models.CharField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_api.players')),
            ],
        ),
    ]
