# Generated by Django 3.1.2 on 2021-03-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apiKey',
            field=models.CharField(max_length=26),
        ),
    ]
