# Generated by Django 3.1.2 on 2021-03-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_api', '0002_auto_20210306_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_of_request',
            field=models.IntegerField(default=0),
        ),
    ]
