# Generated by Django 3.1.2 on 2021-02-27 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_api', '0002_remove_players_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='Year',
            new_name='year',
        ),
    ]
