# Generated by Django 3.1.2 on 2021-02-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_api', '0003_auto_20210226_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='players',
            name='weight',
            field=models.CharField(max_length=10),
        ),
    ]
