# Generated by Django 3.1.2 on 2021-03-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_api', '0004_auto_20210226_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='player',
        ),
        migrations.AddField(
            model_name='statistics',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='player', to='nba_api.players'),
        ),
    ]
