# Generated by Django 3.1.2 on 2021-03-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_api', '0005_auto_20210228_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='player',
        ),
        migrations.AddField(
            model_name='players',
            name='stats',
            field=models.ManyToManyField(blank=True, related_name='stats', to='nba_api.statistics'),
        ),
    ]
